name: Deploy on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PETERMALINA }}
      - uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev/petermalina/petermalina-site
          username: _json_key
          password: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PETERMALINA }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: europe-west3-docker.pkg.dev/petermalina/petermalina-site/petermalina-site:latest
          file: ./Dockerfile